import sys
import matplotlib.pyplot as plt
import random

n = int(sys.argv[1])

numbers = []
for i in xrange(1,n):
	numbers.append(random.random())

print 'Numbers generated by python'
print numbers

plt.hist(numbers)
plt.title("Histogram")
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.show()
